version: '2'
services:
  esaude-emr-poc:
    image: esaude-docker-poc-docker.bintray.io/poc:2.0.1
    ports:
      - "80:80"
    container_name: esaude-emr-poc
    networks:
      - network
    hostname: esaude-emr-poc
    restart: unless-stopped
networks:
  network:
volumes:
  data:
